services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: lzinn/divekit-dashboard:latest
    restart: always
    ports:
      - '${REACT_APP_BACKEND_PORT}:8080'               # default is 8080
    environment:
      GITLAB_SERVER: $GITLAB_SERVER                 # default server is https://git.archi-lab.io
      GITLAB_TOKEN: $GITLAB_TOKEN                   # ! needs to be set in .env !
      REACT_APP_BACKEND_SERVER: $REACT_APP_BACKEND_SERVER # default is http://localhost
      REACT_APP_BACKEND_PORT: $REACT_APP_BACKEND_PORT  # default is 8080
