services:
  frontend:
    image: lzinn/divekit-dashboard:frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_FRONTEND_PORT}:3000"
    environment:
      - REACT_APP_BACKEND_PORT=$DOCKER_BACKEND_PORT
  backend:
    image: lzinn/divekit-dashboard:backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - '${DOCKER_BACKEND_PORT}:8080'
    environment:
      - GITLAB_SERVER=$GITLAB_SERVER  # default server is https://git.archi-lab.io
      - GITLAB_TOKEN=$GITLAB_TOKEN
      - DOCKER_FRONTEND_PORT=${DOCKER_FRONTEND_PORT}